### ISSUE TITLE
Error "Team name cannot be null!"

### ISSUE THREAD

**Issue by tboba** [missionarydev/board#5]
Hi. I'm using plugin `board` on my server. Rarely, it spams an error "Team name cannot be null!" 🤔 

Spigot version: "Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)"

```
[15:28:10 WARN]: [MyPlugin] Task #2981 for MyPlugin v1.0 generated an exception
java.lang.IllegalArgumentException: Team name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scoreboard.CraftScoreboard.getTeam(CraftScoreboard.java:146) ~[patched_1.14.4.jar:git-Paper-243]
        at me.missionary.board.board.Board.update(Board.java:102) ~[?:?]
        at me.missionary.board.board.tasks.BoardUpdateTask.lambda$run$2(BoardUpdateTask.java:23) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_275]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_275]
        at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1577) ~[?:1.8.0_275]
        at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3606) ~[?:1.8.0_275]
        at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1602) ~[?:1.8.0_275]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_275]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_275]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_275]
        at me.missionary.board.board.tasks.BoardUpdateTask.run(BoardUpdateTask.java:23) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by tboba** [comment]
Okay, I learned that this warning appears only when the number of lines is higher than 15, which I assume is a number of the maximum shown lines on the scoreboard. Is it possible to add an error when the Player is trying to show higher number of lines than 15? This error should also end all refresh tasks to don't show the same warning every x seconds/ticks.

**Comment by missionarydev** [comment]
Version 1.14 of Minecraft is not "officially" supported with this library, it's geared more towards 1.7.x & 1.8.x. I'm not familiar with the newer versions of Minecraft and what the limitations of scoreboards are with those versions, although nothing looks like it has changed. Feel free to make a PR with any added changes.

* For the 16 length entry limit, I'd just add something here https://github.com/missionarydev/board/blob/master/src/main/java/me/missionary/board/board/Board.java#L80 or in your implementation of the [BoardProvider](https://github.com/missionarydev/board/blob/master/src/main/java/me/missionary/board/provider/BoardProvider.java), example [here](https://github.com/missionarydev/board/blob/master/src/main/java/me/missionary/board/example/ExampleUsage.java).
* The IllegalArgumentException w/ team names being null may not occur for each online player since the board could show different content per player.

**Comment by tboba** [comment]
@missionarydev sure!
I'll create a PR with that changes on my free time.
